Pizzaordering/notdominos/urls.py
from django.urls import path, include
from . import views
from .forms import *

urlpatterns = [
    path('', views.index, name="index"),
    path('contact.html', views.contact, name ="contact"),
    path("order.html", views.order, name="order"),
    path('register/', views.UserSignupView.as_view(), name="register"),
    path('login/', views.LoginView.as_view(template_name="login.html",
         authentication_form=UserLoginForm), name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('orders/', views.orders_history, name="orders_history"),
    path('order/', views.order, name="order"),
    path('orders/delivery_details/',
         views.delivery_details, name="delivery_details"),
    path('orders/order_confirmation/<int:order_id>/', views.order_confirmation,
         name="order_confirmation"),
]

Pizzaordering/pizzaorder/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include('notdominos.urls')),
    path("admin/", admin.site.urls),
]

Pizzaordering/notdominos/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import AbstractUser

from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    email = models.EmailField('Email', unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()


class Size(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return self.name


class Crust(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Sauce(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Cheese(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Topping(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Pizza(models.Model):
    size = models.ForeignKey(Size, on_delete=models.CASCADE, null=True)
    crust = models.ForeignKey(Crust, on_delete=models.CASCADE, null=True)
    sauce = models.ForeignKey(Sauce, on_delete=models.CASCADE, null=True)
    cheese = models.ForeignKey(Cheese, on_delete=models.CASCADE, null=True)
    toppings = models.ManyToManyField(Topping, blank=True)

    def __str__(self):
        return f"{self.size} {self.crust} Pizza"


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pizza = models.ManyToManyField(Pizza)
    name = models.CharField(max_length=100)
    street_address = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    county = models.CharField(max_length=100, default='')
    zip_code = models.CharField(max_length=100, default='')
    country = models.CharField(max_length=100, default='')
    card_number = models.CharField(max_length=19)
    card_expiry_month = models.PositiveIntegerField()
    card_expiry_year = models.PositiveIntegerField()
    card_cvv = models.PositiveIntegerField()
    order_date = models.DateTimeField(auto_now_add=True)
    delivery_date = models.DateTimeField(null=True)
    delivery_time = models.TimeField(null=True)

    def __str__(self):
        return f"Order for {self.name}"

Pizzaordering/notdominos/forms.py
import datetime
from .models import Order
from .models import *
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import CheckboxSelectMultiple
from django.db import transaction
from django.core.exceptions import ValidationError


class PizzaForm(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = ['size', 'crust', 'sauce', 'cheese', 'toppings']
        widgets = {
            'toppings': CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['size'].queryset = Size.objects.all()
        self.fields['crust'].queryset = Crust.objects.all()
        self.fields['sauce'].queryset = Sauce.objects.all()
        self.fields['cheese'].queryset = Cheese.objects.all()
        self.fields['toppings'].queryset = Topping.objects.all()


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['name', 'street_address', 'city', 'county', 'zip_code', 'country', 'card_number',
                  'card_expiry_month', 'card_expiry_year', 'card_cvv', 'delivery_date', 'delivery_time']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'street_address': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'county': forms.TextInput(attrs={'class': 'form-control'}),
            'zip_code': forms.TextInput(attrs={'class': 'form-control'}),
            'country': forms.TextInput(attrs={'class': 'form-control'}),
            'card_number': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '1234 5678 9012 3456', 'inputmode': 'numeric', 'pattern': '[0-9]{4} [0-9]{4} [0-9]{4} [0-9]{4}'}),
            'card_expiry_month': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'MM', 'maxlength': '2', 'pattern': '[0-9]{2}', 'inputmode': 'numeric', 'min': '1', 'max': '12'}),
            'card_expiry_year': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'YYYY', 'maxlength': '4', 'pattern': '[0-9]{4}', 'inputmode': 'numeric', 'min': '2024', 'max': '2050'}),
            'card_cvv': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '123', 'maxlength': '3'}),
            'delivery_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date', 'format': 'yyyy-mm-dd'}),
            'delivery_time': forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}),
        }

        def clear(self):
            cleaned_data = super().clean()
            delivery_date = cleaned_data.get('delivery_date')
            delivery_time = cleaned_data.get('delivery_time')
            card_expiry_month = cleaned_data.get(
                'card_expiry_month')  # Fix: Added this line
            card_expiry_year = cleaned_data.get(
                'card_expiry_year')  # Fix: Added this line
            if delivery_date < datetime.date.today():
                raise ValidationError('Delivery date cannot be in the past')
            if delivery_date == datetime.date.today() and delivery_time < datetime.datetime.now().time():
                raise ValidationError('Delivery time cannot be in the past')
            if card_expiry_month < datetime.date.today().month and card_expiry_year == datetime.date.today().year:
                raise ValidationError('Card has expired')
            if card_expiry_year < datetime.date.today().year:
                raise ValidationError('Card has expired')


class UserSignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_admin = False
        user.email = self.cleaned_data['username']
        user.save()
        return user


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

Pizzaordering/notdominos/views.py
from django.shortcuts import render
import re
from django.shortcuts import render, get_object_or_404
import random
from .models import *
from .forms import *
from django.views.generic import CreateView
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.utils.timezone import now
from django.http import JsonResponse
# Create your views here.

def index(request):
    return render(request, 'index.html')

def contact(request):
    return render(request, 'contact.html')


class UserSignupView(CreateView):
    model = User
    form_class = UserSignupForm
    template_name = 'user_signup.html'

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('/')


class UserLoginView(LoginView):
    template_name = 'login.html'


def logout_user(request):
    logout(request)
    return redirect("/")


@login_required()
def order(request):
    if request.method == 'POST':
        form = PizzaForm(request.POST)
        if form.is_valid():
            pizza = form.save()
            request.session['pizza_id'] = pizza.id
            return redirect('delivery_details')
    else:
        form = PizzaForm()
    return render(request, 'order.html', {'form': form})


@login_required()
def delivery_details(request):
    pizza_id = request.session.get('pizza_id')
    if not pizza_id:
        return redirect('create_pizza')

    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user
            order.save()
            selected_pizza = Pizza.objects.get(pk=pizza_id)
            order.pizza.add(selected_pizza)
            del request.session['pizza_id']
            return redirect('order_confirmation', order_id=order.id)
    else:
        form = OrderForm()
    return render(request, 'delivery_details.html', {'form': form})


@login_required()
def order_confirmation(request, order_id):
    order = get_object_or_404(Order, id=order_id)

    # check if the logged in user is the owner of the order
    if request.user != order.user:
        # redirect the user to main page
        return redirect("/orders/")
    return render(request, 'order_confirmation.html', {'order': order})


@login_required()
def orders_history(request):
    user = request.user
    orders = Order.objects.filter(user=user)
    return render(request, 'order_history.html', {'orders': orders})

Pizzaordering/notdominos/templates/base.html
{% load static %}

<html>
    <style>
        .logo {
            text-align: center;
            background-color: red;
            color: white;
            padding: 10px;
        }
        .navbar {
            text-align: center;
            background-color: black;
            color: white;
            padding: 10px;
        }
        .navbar a {
            color: white;
            padding: 14px 20px;
            text-decoration: none;
            text-transform: uppercase;
            font-size: 20px;
        }
        .navbar a:hover {
            background-color: red;
            color: white;
        }
        .maintext {
            text-align: center;
            padding: 20px;
        }
    </style>
    <head>
    </head>
    <body bgcolor="beige">
        <div class="logo">
            <h1> Not Dominos </h1>
        </div>
        <div class="navbar">
            <a href="/">Home</a>
            <a href="{% url 'order' %}">Order</a>
            <a href="{% url 'orders_history' %}">Order History</a>
            <a href="{% url 'contact' %}">Contact</a>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

Pizzaordering/notdominos/templates/contact.html
{% extends "base.html" %}

{% block content %}
        <div class="maintext">
                <h1>Contact Us</h1>
                <p> Email : NotDominos@totallyIpromise.com</p>
                <p> Phone : 123-456-7890</p>
                <p> Address : 1234 Not Dominos Street, Not Dominos City, Not Dominos Country, 12345</p>
        </div>
{% endblock %}

Pizzaordering/notdominos/templates/delivery_details.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h2>Fill in your details</h2>
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">Create</button>
            </form>
        </div>
    </div>
</div>

<style>

</style>

<script>
    // Credit card number formatting script
    document.getElementById('id_card_number').addEventListener('input', function (e) {
        var target = e.target;
        var value = target.value.replace(/\D/g, '').substring(0, 16);
        var newValue = '';

        for (var i = 0; i < value.length; i++) {
            if (i % 4 === 0 && i > 0) {
                newValue += ' ';
            }
            newValue += value.charAt(i);
        }

        target.value = newValue;
    });
</script>
{% endblock %}

Pizzaordering/notdominos/templates/index.html
{% extends "base.html" %}

{% block content %}
        <div class="maintext">
            <p>Not Dominos is a pizza delivery service that is not affiliated with Dominos.</p>
            <p>Our pizza is not made with the freshest ingredients and is not delivered in 30 minutes or less.</p>
            <p>Our pizza is not the best pizza in the world, but it is not the worst either.</p>
            <p>Order now and get a free side of not breadsticks!</p>
            <a href="order.html">Order Now</a>
        </div>
{% endblock %}

Pizzaordering/notdominos/templates/login.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <form action="" method="POST" class="mt-5">
        {% csrf_token %}
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header bg-primary text-white">
                        <h3 class="card-title">Login</h3>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            {{ form.as_p }}
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary btn-block mt-3">Submit</button>
                        <p>don't have an account? <a href="{% url 'register' %}">create an account</a></p>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<style>
    #id_username,
    #id_password {
        width: 100%;
        box-sizing: border-box;
    }
</style>
{% endblock %}

Pizzaordering/notdominos/templates/order.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card mt-5">
                <div class="card-header bg-primary text-white">
                    <h2 class="mb-0">Create a New Pizza</h2>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.as_p }}
                        </div>
                        <button type="submit" class="btn btn-primary">Order</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    p {
        left: 0;
        margin-right: 10px;
        margin-top: 10px;
        display: inline-block;
    }

    p label {
        font-size: large;
        margin-right: 10px;
        margin-top: 15px;
    }

    #id_toppings {
        margin-left: 10px;
        margin-top: 0;
    }

    @media screen and (max-width: 600px) {
        p {
            left: 0;
            margin-right: 5px;
            margin-left: 5px;
            display: block;
        }

        p label {
            margin-bottom: 10px;
            margin-top: 7.5px;
        }

        #id_size,
        #id_crust,
        #id_cheese,
        #id_sauce {
            width: 100%;
        }

        #id_toppings {
            margin-left: 5px;
        }
    }
</style>

{% endblock %}

Pizzaordering/notdominos/templates/order_confirmation.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1 class="display-4">Order Confirmation</h1>
    <p class="lead">Thank you for your order {{ order.user }}. Your order number is {{ order.id }}.</p>
    <p class="lead">Your delivery time is {{ order.delivery_date|date:'d-m-Y' }} at {{ order.delivery_time }}</p>
    <p class="lead">Delivery Address: {{ order.street_address }}, {{ order.city }}, {{ order.country }},
        {{order.zip_code}}</p>
    <p class="lead">Your ordered pizza:</p>
    <ul class="list-group">
        {% for pizza in order.pizza.all %}
        <li class="list-group-item">Pizza Size: {{ pizza.size }}</li>
        <li class="list-group-item">Crust: {{ pizza.crust }}</li>
        <li class="list-group-item">Toppings:
            {% if pizza.toppings.all %}
            {{ pizza.toppings.all|join:", " }}
            {% else %}
            No Toppings
            {% endif %}
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

Pizzaordering/notdominos/templates/order_history.html
{% extends 'base.html' %}

{% block content %}
{% if orders %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card mt-5">
                <div class="card-header bg-primary text-white">
                    <h4 class="mb-0">Your Orders</h4>
                </div>
                <!-- Button to order another pizza -->
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-md-6 text-center mb-4">
                            <a href="{% url 'order' %}" class="btn btn-primary btn-lg mt-4">Order Pizza</a>
                        </div>
                    </div>
                </div>
                <ul class="list-group list-group-flush">
                    {% for order in orders %}
                    <li class="list-group-item">
                        <h5 class="card-title">Title: {{ order.name }}</h5>
                        <p>Order Number: {{order.id}}</p>
                        <p>Delivery Address: {{ order.street_address }}, {{ order.city }}, {{ order.country }},
                            {{ order.zip_code }}</p>
                        <p>Date ordered: {{ order.order_date }}</p>
                        <ul class="list-group">
                            {% for pizza in order.pizza.all %}
                            <li class="list-group-item">Pizza Size: {{ pizza.size }}</li>
                            <li class="list-group-item">Crust: {{ pizza.crust }}</li>
                            <li class="list-group-item">Toppings:
                                {% if pizza.toppings.all %}
                                {{ pizza.toppings.all|join:", " }}
                                {% else %}
                                No Toppings
                                {% endif %}
                            </li>

                            {% endfor %}
                        </ul>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3 text-center">
            <h3 class="mt-5">You haven't ordered any pizza</h3>
            <a href="{% url 'order' %}" class="btn btn-primary btn-lg mt-3">Order Pizza</a>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

Pizzaordering/notdominos/templates/user_signup.html
{% extends 'base.html' %}

{% block title %}
User Signup
{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-header bg-primary text-white">
                    <h3 class="card-title">User Signup</h3>
                </div>
                <div class="card-body">
                    <form action="." method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.as_p }}
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}